# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uitp2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
from brainflow.board_shim import BoardShim, BrainFlowInputParams, BoardIds
from brainflow.data_filter import DataFilter
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import scipy.signal as sig
import scipy.io as sio
import pandas as pd
from pyqtgraph import GraphicsLayoutWidget

import datetime



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.botonera = QtWidgets.QHBoxLayout()
        self.botonera.setObjectName("botonera")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

         ## Boton conectar BCI
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.comunica_cyton)


        self.verticalLayout_3.addWidget(self.pushButton)
        self.botonera.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        ## Boton inicio
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.iniciar_registro)

        self.verticalLayout_4.addWidget(self.pushButton_2)

        ## Boton fin
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2.clicked.connect(self.fin_registro)


        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.botonera.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)


        ### input nombre archivo
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

    
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.botonera.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.botonera)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")

        ## Grafica
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_5)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView = PlotWidget(self.centralwidget)

        self.verticalLayout.addWidget(self.graphicsView)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TP 2 - PSB - 2022 - Grupo 3"))
        self.groupBox.setTitle(_translate("MainWindow", "Controles"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Conectar"))
        self.pushButton.setText(_translate("MainWindow", "Open BCI"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Registro"))
        self.pushButton_2.setText(_translate("MainWindow", "Inicio"))
        self.pushButton_3.setText(_translate("MainWindow", "Fin"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Frecuencia"))
        self.label.setText(_translate("MainWindow", "frecccccccccc"))
        self.label_2.setText(_translate("MainWindow", "Ingrese nombre del archivo a crear"))
        # self.groupBox_5.setTitle(_translate("MainWindow", "Grafico"))


    ## metodos propios

    ###########################################################################################################################################
    '''La siguiente función permite la conexión con la placa openBCI para luego obtener los datos que provienen de esta'''
    ###########################################################################################################################################
    def comunica_cyton(self):

        #Para leer datos de la placa con info detallada 
        BoardShim.enable_dev_bpantompkinsoard_logger()
    
        #Parametros de entrada para el método de prepare_session
        params=BrainFlowInputParams()
        #Puerto serie de donde se van a leer los datos --> Fijarnos cual es en nuestro caso
        params.serial_port='COM7'

        board_id = BoardIds.CYTON_BOARD.value 
        self.board = BoardShim(board_id, params)
    
        #Prepara la transmisión
        self.board.prepare_session()

        #Configuración de los comandos
    
        #Se ponen todos los canales en Default 
        self.board.congif_board('d')

        #Configuracion del canal 1 -> Encendido // Ganancia de 24 // Fuente de entrada del canal ADC // Generación de BIAS // Desconecta entrada con SRB2 // Desconecta entrada con SRB1
        self.board.config_board('x1060100X')

        #Apaga los demas canales
        self.board.config_board('2')
        self.board.config_board('3')
        self.board.config_board('4')
        self.board.config_board('5')
        self.board.config_board('6')
        self.board.config_board('7')
        self.board.config_board('8')

    ###########################################################################################################################################
    '''Para iniciar el registro de la placa OpenBCI se debe apretar inicio registro que hace lo siguiente'''
    ###########################################################################################################################################
    
    def iniciar_registro(self):
        print("Inicio del registro de datos")
        self.board.start_stream(900000)                                     #Comienza a transmitir los datos y los guarda en un buffer de 900k
        
        self.Fs=250
        self.vector = np.ndarray(shape=(1), dtype= np.float64)
        self.guardar = np.ndarray(shape=(1), dtype= np.float64)
        self.tiempo=[]
        self.guardart=[]
     
        self.contador=0                                                                                     #Contador y timer para iniciar el bucle
        self.timerB = QtCore.QTimer()
        self.timerB.timeout.connect(self.bucleBCI)
        self.timerB.start(2000)

    ###########################################################################################################################################
    '''Bucle para el OpenBCI'''
    ###########################################################################################################################################

    def bucleBCI(self):
        
        tiempo=np.arange(2*self.contador, 2+2*self.contador,1/self.Fs)                                     #Vector con los segundos
        self.contador+=1
        paquete=self.board.get_board_data()                                                                #Obtiene datos de la placa y los elimina (2seg con f = 250 -> 500 muestras)
        paquete=paquete[1]                                                                                 #Nos quedamos con el canal ECG = 1 ¿?
        self.guardar = np.hstack((self.guardar, paquete))                                                       #Guarda datos para el archivo CSV

        self.vector = np.hstack((self.vector, paquete))         
        self.tiempo = np.hstack((self.tiempo, tiempo)) ## tiempo para el grafico, chequear                                                    

        if (len(self.vector)> (10*self.Fs)):                                                                    #Si el vector tiene 10seg (12seg) 
            self.vector=self.vector[(2*self.Fs):]                                                          #Se eliminan 2seg para que quede en 10seg
            self.tiempo=self.tiempo[(2*self.Fs):]
            self.deteccion_QRS(self.vector,self.Fs)                                                        #Calcula la frecuencia cardiaca a partir de 10seg 

        self.graficar(self.vector,self.tiempo)                                                             #Va graficando la señal ECG cada 2seg

    
    ###########################################################################################################################################
    '''Función para graficar en la interfaz'''
    ###########################################################################################################################################

    def graficar(self,vector,tiempo):
        self.graphicsView.clear()                                                                         
        self.graphicsView.plot(tiempo,vector)                                                              
        self.graphicsView.showLabel('left',show=True)
        self.graphicsView.showLabel('bottom',show=True)
        self.graphicsView.setLabels(title="Señal ECG",bottom="Tiempo [s]",left="Amplitud [uV]")


    ###########################################################################################################################################
    '''Detección QRS'''
    ###########################################################################################################################################

    def deteccion_QRS(self,señal,fs):

        copia=señal.copy()
        #1. Preacondicionamiento: Pasa banda 5 a 15Hz                                                                         
        w1=5*2/fs                                                                                   #Frecuencias de corte       
        w2=15*2/fs
        N=3                                                                                         #Orden del filtro
        b,a=sig.butter(N,[w1,w2],'bandpass',analog=False)                                           #Coeficientes del filtro IIR (b numerador, a denominador)

        señal=sig.filtfilt(b,a,señal,axis=0)                                                        #Se le aplica el filtro a la señal            
        ecg_b= señal/np.max(np.abs(señal))                                                          #ECG con preacondicionamiento normalizado

        '''#Grafico de la señal filtrada 
        plt.plot(ecg_b)
        plt.title("Preacondicionamiento ECG: Filtro pasa-banda")
        plt.xlabel("Muestras")
        plt.ylabel("Amplitud normalizada")
        plt.show()'''

        #2. Filtro derivativo

        b = [1*fs/8,2*fs/8,0,-2*fs/8,-1*fs/8]                                                       #Coeficientes del filtro derivativo
        ecg_d=sig.filtfilt(b,1,ecg_b)                                                               #Se le aplica el filtro
        ecg_d=ecg_d/np.max(ecg_d)                                                                   #Se normaliza 

        '''#Grafico de la señal  
        if (self.contador==1):
                plt.plot(ecg_d)
                plt.title("ECG luego del filtro derivativo")
                plt.xlabel("Muestras")
                plt.ylabel("Amplitud normalizada")
                plt.show()'''

        #3. Cuadrado: Se eleva la señal obtenida en el punto anterior para que quede todo positivo 

        ecg_c= np.power(ecg_d,2)                                                                    

        '''#Grafico
        if (self.contador==1):
                plt.plot(ecg_c)
                plt.title("ECG luego de elevar al cuadrado")
                plt.xlabel("Muestras")
                plt.ylabel("Amplitud normalizada")
                plt.show()'''

        #4. Integración: Se integra para saber cuales picos son realmente QRS (duran más tiempo) y cuales no 
        L=round(0.150*fs)                                                                             #Tamaño de la ventana
        ecg_i= np.zeros(len(ecg_c))
        suma=0

        for i in range(L):                                                                            #Primera ventana           
            suma+=ecg_c[i]
            ecg_i[i]=suma/L

        for i in range(L,len(ecg_c)):                                                                 
            suma+=ecg_c[i]
            suma-=ecg_c[i-L]
            ecg_i[i]=suma/L

        '''#Grafico
        if (self.contador==1):
                plt.plot(ecg_i)
                plt.title("ECG luego de integrar")
                plt.xlabel("Muestras")
                plt.ylabel("Amplitud normalizada")
                plt.show()'''

        #Buscamos cuantos picos QRS hay

        picos,_= sig.find_peaks(ecg_i,height=0.20,distance=0.75*fs)                                  #Función que devuelve el indice de los picos, la altura y distancia se determino al observar el ECG de prueba       
        frecuencia=len(picos)*6                                                                      #Calculo de la frecuencia cardiaca = picos QRS cada 10seg * 6 = picos QRS o latidos por minuto
        frec=str(frecuencia)
        self.label.setText(frec)

    ###########################################################################################################################################
    '''Finalización del registro: Se para el Timer para que deje de hacer el bucle, luego se para de transmitir y se cierra la sesión con la placa'''
    ###########################################################################################################################################

    def fin_registro(self):

        print("Fin del registro")
        self.timerB.stop()                                                                         #Se para de realizar el ciclo de bucleBCI                                                     
        self.board.stop_stream()                                                                   #Deja de transmitir
        self.board.release_session()                                                               #Se cierra la sesión con la placa

        #data={'Tiempo [s]': self.guardart, 'ECG [uV]': self.guardar}                        #Diccionario con los datos de toda la sesión
        data={'ECG [uV]': self.guardar}     
        df=pd.DataFrame(data)          
        
        #Se guardan los datos en un archivo csv
        if (self.lineEdit.text() ) == "":
            df.to_csv('ECG' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") +'.csv',index=False)
        else:
            df.to_csv(self.lineEdit.text()+'.csv',index=False)
                               

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
